service: croupon-serverless

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  # - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.constant.REGION}

custom:
  constant: ${file(env.yml):CONSTANT}
  environment: ${file(env.yml):${opt:stage}}

resources:
  - ${file(resources/dynamodb.yml)}  
  - ${file(resources/iam-policies.yml)}

functions:
  app:
    handler: src/api/server.handler
    events:
      - http:
          path: /
          method: get
